#!/usr/bin/env python3
import subprocess
import sys
from watchgod import watch
for changes in watch('./src/pyapp'):
  out = subprocess.check_output("./src/update_docs", shell=True)
  sys.stdout.write(out.decode("utf-8"))
